export const PopularApps = [
"Life Made WI-Fi Touchscreen Photo Frame", 
"Google Play Books", 
"Messenger â€“ Text and Video Chat for Free", 
"WhatsApp Messenger", 
"Google Chrome: Fast & Secure", 
"Gmail", 
"Hangouts", 
"Skype - free IM & video calls", 
"Google Play Games", 
"Subway Surfers", 
"Facebook", 
"Instagram", 
"Google+", 
"Google Photos", 
"Maps - Navigate & Explore", 
"Google Street View", 
"Google", 
"Google Drive", 
"YouTube", 
"Google Play Movies & TV", 
"Google News", 
"Viber Messenger", 
"imo free video calls and chat", 
"Google Duo - High Quality Video Calls", 
"UC Browser - Fast Download Private & Secure", 
"LINE: Free Calls & Messages", 
"Candy Crush Saga", 
"Temple Run 2", 
"Pou", 
"My Talking Tom", 
"Facebook Lite", 
"Snapchat", 
"Google Translate", 
"SHAREit - Transfer & Share", 
"Gboard - the Google Keyboard", 
"Microsoft Word", 
"Dropbox", 
"Google Calendar", 
"Cloud Print", 
"MX Player", 
"Twitter", 
"Flipboard: News For Our Time", 
"Clean Master- Space Cleaner & Antivirus", 
"Samsung Health", 
"Security Master - Antivirus", "VPN", "AppLock", "Booster", 
"Wattpad ðŸ“– Free Books", 
"Amazon Kindle", 
"OfficeSuite : Free Office + PDF Editor", 
"Messenger Lite: Free Calls & Messages", 
"Firefox Browser fast & private", 
"Yahoo Mail â€“ Stay Organized", 
"imo beta free calls and text", 
"Opera Mini - fast web browser", 
"Opera Browser: Fast and Secure", 
"Who", 
"WeChat", 
"UC Browser Mini -Tiny Fast Private & Secure", 
"Android Messages", 
"Telegram", 
"GO SMS Pro - Messenger", "Free Themes", "Emoji", 
"BBM - Free Calls & Messages", 
"KakaoTalk: Free Calls & Text", 
"Truecaller: Caller ID", "SMS spam blocking & Dialer", 
"Duolingo: Learn Languages Free", 
"Netflix", 
"Hotstar", 
"Talking Angela", 
"IMDb Movies & TV", 
"Talking Ben the Dog", 
"Google Pay", 
"Period Tracker - Period Calendar Ovulation Tracker", 
"ROBLOX", 
"slither.io", 
"Clash Royale", 
"Helix Jump", 
"Angry Birds Rio", 
"Plants vs. Zombies FREE", 
"Sonic Dash", 
"Candy Crush Soda Saga", 
"Clash of Clans", 
"PAC-MAN", 
"8 Ball Pool", 
"Angry Birds Classic", 
"Flow Free", 
"Zombie Tsunami", 
"Hill Climb Racing", 
"Minion Rush: Despicable Me Official Game", 
"Farm Heroes Saga", 
"My Talking Angela", 
"Cut the Rope FULL FREE", 
"Sniper 3D Gun Shooter: Free Shooting Games - FPS", 
"Cooking Fever", 
"Score! Hero", 
"Garena Free Fire", 
"Roll the BallÂ® - slide puzzle", 
"Talking Tom Gold Run", 
"Dream League Soccer 2018", 
"Traffic Racer", 
"Hill Climb Racing 2", 
"Hungry Shark Evolution", 
"Piano Tiles 2â„¢", 
"PokÃ©mon GO", 
"Extreme Car Driving Simulator", 
"Trivia Crack", 
"Angry Birds 2", 
"Yes day", 
"Crossy Road", 
"Shadow Fight 2", 
"Agar.io", 
"Bus Rush: Subway Edition", 
"Jetpack Joyride", 
"Tumblr", 
"Pinterest", 
"LinkedIn", 
"Badoo - Free Chat & Dating App", 
"Tango - Live Video Broadcast", 
"Wish - Shopping Made Fun", 
"AliExpress - Smarter Shopping", "Better Living", 
"eBay: Buy & Sell this Summer - Discover Deals Now!", 
"Amazon Shopping", 
"Flipkart Online Shopping App", 
"B612 - Beauty & Filter Camera", 
"YouCam Makeup - Magic Selfie Makeovers", 
"BeautyPlus - Easy Photo Editor & Selfie Camera", 
"Sweet Selfie - selfie camera", "beauty cam", "photo edit", 
"YouCam Perfect - Selfie Photo Editor", 
"Cymera Camera- Photo Editor", "Filter", "Collage", "Layout", 
"LINE Camera - Photo editor", 
"Candy Camera - selfie", "beauty camera", "photo editor", 
"Camera360: Selfie Photo Editor with Funny Sticker", 
"Photo Editor Pro", 
"Retrica", 
"PicsArt Photo Studio: Collage Maker & Pic Editor", 
"Photo Collage Editor", 
"Z Camera - Photo Editor", "Beauty Selfie", "Collage", 
"PhotoGrid: Video & Pic Collage Maker", "Photo Editor", 
"Booking.com Travel Deals", 
"TripAdvisor Hotels Flights Restaurants Attractions", 
"Google Earth", 
"Cache Cleaner-DU Speed Booster (booster & cleaner)", 
"Calculator", 
"Device Help", 
"Account Manager", 
"Samsung Calculator", 
"Google Korean Input", 
"Share Music & Transfer Files - Xender", 
"Tiny Flashlight + LED", 
"GO Keyboard - Cute Emojis", "Themes and GIFs", 
"Speedtest by Ookla", 
"CM Locker - Security Lockscreen", 
"Applock", 
"ZEDGEâ„¢ Ringtones & Wallpapers", 
"CM Launcher 3D - Theme", "Wallpapers", "Efficient", 
"APUS Launcher - Theme", "Wallpaper", "Hide Apps", 
"Hola Launcher- Theme", "Wallpaper", 
"Backgrounds HD (Wallpapers)", 
"GO Keyboard - Emoticon keyboard", "Free Theme", "GIF", 
"Adobe Acrobat Reader", 
"Microsoft Outlook", 
"Microsoft Excel", 
"Microsoft OneDrive", 
"Microsoft OneNote", 
"Google Keep", 
"ES File Explorer File Manager", 
"Google Docs", 
"Evernote â€“ Organizer", "Planner for Notes & Memos", 
"Microsoft PowerPoint", 
"Samsung Notes", 
"SwiftKey Keyboard", 
"Google Sheets", 
"WPS Office - Word", "Docs", "PDF", "Note", "Slide & Sheet", 
"Google Slides", 
"ColorNote Notepad Notes", 
"Motorola FM Radio", 
"Motorola Gallery", 
"VLC for Android", 
"Waze - GPS", "Maps", "Traffic Alerts & Live Navigation", 
"Uber", 
"Super Mario Run", 
"Glow Hockey", 
"Asphalt 8: Airborne", 
"Lep's World 2 ðŸ€ðŸ€", 
"Bible", 
"Tik Tok - including musical.ly", 
"BIGO LIVE - Live Stream", 
"Hay Day", 
"Dubsmash", 
"Fruit NinjaÂ®", 
"Vector", 
"Dr. Driving", 
"Bike Race Free - Top Motorcycle Racing Games", 
"3D Bowling", 
"Smash Hit", 
"Temple Run", 
"Lookout Security & Antivirus", 
"Talking Tom Cat 2", 
"Google Now Launcher", 
"Geometry Dash Lite", 
"Talking Ginger", 
"Where's My Water? Free", 
"Talking Tom Cat", 
"Kik", 
"Tom Loves Angela", 
"Ant Smasher by Best Cool & Fun Games", 
"Parallel Space - Multiple accounts & Two face", 
"360 Security - Free Antivirus", "Booster", "Cleaner", 
"S Photo Editor - Collage Maker ", "Photo Collage", 
"Samsung Smart Switch Mobile", 
"Tinder", 
"VivaVideo - Video Editor & Photo Movie", 
"VideoShow-Video Editor", "Video Maker", "Beauty Camera", 
"Talking Tom & Ben News", 
"Avast Mobile Security 2018 - Antivirus & App Lock", 
"GO Launcher - 3D parallax Themes & HD Wallpapers", 
"Angry Birds Star Wars", 
"AR effect", 
"Mobile Legends: Bang Bang", 
"Audiobooks from Audible", 
"AVG AntiVirus 2018 for Android Security", 
"Banana Kong", 
"Bitmoji â€“ Your Personal Emoji", 
"VK", 
"Skater Boy", 
"Bubble Witch 2 Saga", 
"Battery Doctor-Battery Life Saver & Battery Cooler", 
"CamScanner - Phone PDF Creator", 
"FIFA Soccer", 
"Automatic Call Recorder", 
"Anti-virus Dr.Web Light", 
"DU Battery Saver - Battery Charger & Battery Life", 
"Modern Combat 5: eSports FPS", 
"Farm Heroes Saga", 
"File Commander - File Manager/Explorer", 
"Photo Editor Collage Maker Pro", 
"Sketch - Draw & Paint", 
"Indeed Job Search", 
"Docs To Goâ„¢ Free Office Suite", 
"Facebook Pages Manager", 
"Secure Folder", 
"Contacts", 
"free video calls and chat", 
"CM Browser - Ad Blocker ", "Fast Download ", "Privacy", 
"Dolphin Browser - Fast", "Private & AdblockðŸ¬", 
"Mail.Ru - Email App", 
"YouTube Kids", 
"Talking Ginger 2", 
"Amazon Prime Video", 
"Twitch: Livestream Multiplayer Games & Esports", 
"PlayStation App", 
"PayPal", 
"Calorie Counter - MyFitnessPal", 
"Samsung+", 
"Hello Kitty Nail Salon", 
"Kick the Buddy", 
"Magic Tiles 3", 
"Bubble Witch 3 Saga", 
"Granny", 
"Candy Crush Jelly Saga", 
"Gardenscapes", 
"Toy Blast", 
"Bowmasters", 
"Block Craft 3D: Building Simulator Games For Free", 
"Love Balls", 
"Snake VS Block", 
"PUBG MOBILE", 
"Episode - Choose Your Story", 
"Castle Clash: Heroes of the Empire US", 
"MARVEL Contest of Champions", 
"Summoners War", 
"Lords Mobile: Battle of the Empires - Strategy RPG", 
"Doodle Jump", 
"Swamp Attack", 
"Earn to Die 2", 
"Hungry Shark World", 
"DEAD TARGET: FPS Zombie Apocalypse Survival Games", 
"Anger of stick 5 : zombie", 
"CATS: Crash Arena Turbo Stars", 
"War Robots", 
"GUNSHIP BATTLE: Helicopter 3D", 
"Word Search", 
"Racing in Car 2", 
"Toca Kitchen 2", 
"LEGOÂ® Juniors Create & Cruise", 
"Turbo FAST", 
"Frozen Free Fall", 
"MeetMe: Chat & Meet New People", 
"ooVoo Video Calls", "Messaging & Stories", 
"SKOUT - Meet", "Chat", "Go Live", 
"POF Free Dating App", 
"Zello PTT Walkie Talkie", 
"letgo: Buy & Sell Used Stuff", "Cars & Real Estate", 
"Lazada - Online Shopping & Deals", 
"OLX - Buy and Sell", 
"The birth", 
"Mercado Libre: Find your favorite brands", 
"Myntra Online Shopping App", 
"Groupon - Shop Deals", "Discounts & Coupons", 
"Motorola Camera", 
"Adobe Photoshop Express:Photo Editor Collage Maker"


]